import { hkdf } from "@noble/hashes/hkdf.js";
import { sha256 } from "@noble/hashes/sha2.js";
import {
  CRYPTO_PROTOCOL_VERSION,
  KEY_BYTES,
  RECOVERY_CHECKSUM_BYTES,
  RECOVERY_CHECKSUM_LABEL,
  RECOVERY_GROUP_SIZE,
} from "./constants.ts";
import { rwkHkdfInfo, rwkHkdfSalt } from "./encoding/aad.ts";
import { concat } from "./encoding/bytes.ts";
import { frame } from "./encoding/framing.ts";
import { ProtocolError } from "./errors.ts";
import { assertBytes, assertId, assertVersion, requireSameBytes } from "./validate.ts";

/**
 * Crockford Base32: no `I`, `L`, `O`, `U`, so the common transcription mistakes
 * are unambiguous rather than silently wrong.
 */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const DECODE = new Map<string, number>();
for (let i = 0; i < ALPHABET.length; i++) {
  DECODE.set(ALPHABET[i] as string, i);
}
// Documented Crockford substitutions for hand-copied keys.
DECODE.set("O", 0);
DECODE.set("I", 1);
DECODE.set("L", 1);

export interface DeriveRecoveryWrappingKeyOptions {
  recoveryKey: Uint8Array;
  vaultId: string;
  cryptoVersion?: number;
}

function base32Encode(bytes: Uint8Array): string {
  let out = "";
  let buffer = 0;
  let bits = 0;
  for (const byte of bytes) {
    buffer = (buffer << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      bits -= 5;
      out += ALPHABET[(buffer >>> bits) & 0x1f];
    }
  }
  if (bits > 0) {
    out += ALPHABET[(buffer << (5 - bits)) & 0x1f];
  }
  return out;
}

function base32Decode(text: string, expectedBytes: number): Uint8Array {
  const out = new Uint8Array(expectedBytes);
  let index = 0;
  let buffer = 0;
  let bits = 0;
  for (const char of text) {
    const value = DECODE.get(char);
    if (value === undefined) {
      throw new ProtocolError(`recovery key contains an invalid character: ${char}`);
    }
    buffer = (buffer << 5) | value;
    bits += 5;
    if (bits >= 8) {
      bits -= 8;
      if (index >= expectedBytes) {
        throw new ProtocolError("recovery key is too long");
      }
      out[index++] = (buffer >>> bits) & 0xff;
    }
  }
  if (index !== expectedBytes) {
    throw new ProtocolError(`recovery key must decode to ${expectedBytes} bytes, got ${index}`);
  }
  // Canonical form: the padding bits of the final character must be zero.
  if (bits > 0 && (buffer & ((1 << bits) - 1)) !== 0) {
    throw new ProtocolError("recovery key has non-canonical trailing bits");
  }
  return out;
}

function checksum(recoveryKey: Uint8Array): Uint8Array {
  return sha256(frame([RECOVERY_CHECKSUM_LABEL, recoveryKey])).slice(0, RECOVERY_CHECKSUM_BYTES);
}

function assertRecoveryKeyBytes(value: unknown): Uint8Array {
  const key = assertBytes("recoveryKey", value, { exact: KEY_BYTES });
  if (key.every((b) => b === 0)) {
    throw new ProtocolError("recoveryKey is all zero — not generated by a CSPRNG");
  }
  return key;
}

/**
 * Emergency-Kit representation of a 256-bit Recovery Key:
 * Crockford Base32 over `key || checksum`, in groups of five characters.
 *
 * The checksum only catches transcription errors. It is not a security
 * boundary: the entropy is the 256-bit key itself.
 */
export function formatRecoveryKey(recoveryKey: Uint8Array): string {
  const key = assertRecoveryKeyBytes(recoveryKey);
  const encoded = base32Encode(concat(key, checksum(key)));
  const groups: string[] = [];
  for (let i = 0; i < encoded.length; i += RECOVERY_GROUP_SIZE) {
    groups.push(encoded.slice(i, i + RECOVERY_GROUP_SIZE));
  }
  return groups.join("-");
}

/**
 * Parse a user-typed Recovery Key. Separators and case are irrelevant, the
 * Crockford substitutions (`O`→0, `I`/`L`→1) are applied, and the checksum must
 * match so that a typo is reported as a typo instead of as "wrong key".
 */
export function parseRecoveryKey(text: string): Uint8Array {
  if (typeof text !== "string") {
    throw new ProtocolError("recovery key must be a string");
  }
  const normalized = text.toUpperCase().replace(/[\s\-_.]/g, "");
  if (normalized.length === 0) {
    throw new ProtocolError("recovery key is empty");
  }
  const decoded = base32Decode(normalized, KEY_BYTES + RECOVERY_CHECKSUM_BYTES);
  const key = decoded.slice(0, KEY_BYTES);
  requireSameBytes("recovery key checksum", checksum(key), decoded.slice(KEY_BYTES));
  return assertRecoveryKeyBytes(key);
}

/**
 * RWK = HKDF-SHA-256(IKM = Recovery Key, salt, info, L = 32).
 *
 * The printed Recovery Key is never used directly as an AES key: the Recovery
 * Envelope is wrapped under a vault-bound derivative, so the same kit material
 * cannot open an envelope belonging to a different vault, and a future second
 * use of the recovery secret gets its own domain.
 */
export function deriveRecoveryWrappingKey(opts: DeriveRecoveryWrappingKeyOptions): Uint8Array {
  const recoveryKey = assertRecoveryKeyBytes(opts.recoveryKey);
  const vaultId = assertId("vaultId", opts.vaultId);
  const cryptoVersion = assertVersion(
    "cryptoVersion",
    opts.cryptoVersion ?? CRYPTO_PROTOCOL_VERSION,
  );
  const salt = sha256(rwkHkdfSalt(vaultId));
  const info = rwkHkdfInfo(vaultId, cryptoVersion);
  return hkdf(sha256, recoveryKey, salt, info, KEY_BYTES);
}
