"""initial schema

Revision ID: 4e9316ce2d07
Revises: 
Create Date: 2026-08-17 21:42:39.315615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9316ce2d07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('account_password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=64), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vaults',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('crypto_protocol_version', sa.Integer(), nullable=False),
    sa.Column('active_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_owner_user_id'), 'vaults', ['owner_user_id'], unique=False)
    op.create_table('devices',
    sa.Column('vault_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('user_agent_summary', sa.String(length=512), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id', 'device_id', name='uq_devices_vault_device_id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_devices_vault_id'), 'devices', ['vault_id'], unique=False)
    op.create_table('vault_snapshots',
    sa.Column('vault_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('vault_key_version', sa.Integer(), nullable=False),
    sa.Column('crypto_protocol_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id', 'revision', name='uq_vault_snapshots_vault_revision')
    )
    op.create_index(op.f('ix_vault_snapshots_vault_id'), 'vault_snapshots', ['vault_id'], unique=False)
    # `vaults.active_snapshot_id` is the CAS pointer from docs/vault-revision.md
    # §2 ("active_revision"). It is added via a deferred ALTER TABLE — rather
    # than inline on `vaults` — because `vault_snapshots` did not exist yet
    # when `vaults` was created (the two tables reference each other).
    op.create_foreign_key(
        'fk_vaults_active_snapshot_id',
        'vaults',
        'vault_snapshots',
        ['active_snapshot_id'],
        ['id'],
        deferrable=True,
        initially='DEFERRED',
    )
    op.create_table('encrypted_entries',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('crypto_version', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['vault_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'entry_id', name='uq_encrypted_entries_snapshot_entry')
    )
    op.create_index(op.f('ix_encrypted_entries_snapshot_id'), 'encrypted_entries', ['snapshot_id'], unique=False)
    op.create_table('key_envelopes',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('master', 'device', 'recovery', name='envelope_type'), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('kdf_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('encryption', sa.String(length=32), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.Column('crypto_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'device' AND device_id IS NOT NULL) OR (type != 'device' AND device_id IS NULL)", name='ck_key_envelopes_device_id_requires_device_type'),
    sa.CheckConstraint("(type = 'master' AND kdf_params IS NOT NULL) OR (type != 'master' AND kdf_params IS NULL)", name='ck_key_envelopes_kdf_params_requires_master_type'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['vault_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_envelopes_snapshot_id'), 'key_envelopes', ['snapshot_id'], unique=False)
    op.create_index('uq_key_envelopes_snapshot_device', 'key_envelopes', ['snapshot_id', 'device_id'], unique=True, postgresql_where=sa.text("type = 'device'"))
    op.create_index('uq_key_envelopes_snapshot_singleton_type', 'key_envelopes', ['snapshot_id', 'type'], unique=True, postgresql_where=sa.text("type IN ('master', 'recovery')"))
    op.create_table('webauthn_credentials',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('rp_id', sa.String(length=255), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('transports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prf_supported', sa.Boolean(), nullable=False),
    sa.Column('large_blob_supported', sa.Boolean(), nullable=False),
    sa.Column('user_verification', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_webauthn_credentials_device_id'), 'webauthn_credentials', ['device_id'], unique=False)
    op.create_table('device_key_envelopes',
    sa.Column('vault_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('webauthn_credential_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('encryption', sa.String(length=32), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.Column('crypto_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webauthn_credential_id'], ['webauthn_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id', 'device_id', name='uq_device_key_envelopes_vault_device')
    )
    op.create_index(op.f('ix_device_key_envelopes_device_id'), 'device_key_envelopes', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_key_envelopes_vault_id'), 'device_key_envelopes', ['vault_id'], unique=False)
    op.create_index(op.f('ix_device_key_envelopes_webauthn_credential_id'), 'device_key_envelopes', ['webauthn_credential_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_key_envelopes_webauthn_credential_id'), table_name='device_key_envelopes')
    op.drop_index(op.f('ix_device_key_envelopes_vault_id'), table_name='device_key_envelopes')
    op.drop_index(op.f('ix_device_key_envelopes_device_id'), table_name='device_key_envelopes')
    op.drop_table('device_key_envelopes')
    op.drop_index(op.f('ix_webauthn_credentials_device_id'), table_name='webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index('uq_key_envelopes_snapshot_singleton_type', table_name='key_envelopes', postgresql_where=sa.text("type IN ('master', 'recovery')"))
    op.drop_index('uq_key_envelopes_snapshot_device', table_name='key_envelopes', postgresql_where=sa.text("type = 'device'"))
    op.drop_index(op.f('ix_key_envelopes_snapshot_id'), table_name='key_envelopes')
    op.drop_table('key_envelopes')
    sa.Enum(name="envelope_type").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_encrypted_entries_snapshot_id'), table_name='encrypted_entries')
    op.drop_table('encrypted_entries')
    op.drop_index(op.f('ix_vault_snapshots_vault_id'), table_name='vault_snapshots')
    op.drop_constraint('fk_vaults_active_snapshot_id', 'vaults', type_='foreignkey')
    op.drop_table('vault_snapshots')
    op.drop_index(op.f('ix_devices_vault_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_vaults_owner_user_id'), table_name='vaults')
    op.drop_table('vaults')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
