"""initial schema: vaults, snapshots, envelopes, devices, webauthn, device-key envelopes

Revision ID: 7a5270658214
Revises: 
Create Date: 2026-08-17 21:40:49.388325
"""
from alembic import op
import sqlalchemy as sa


revision = '7a5270658214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crypto_protocol_version', sa.Integer(), nullable=False),
    sa.Column('active_revision', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_user_id'), 'vaults', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_agent_summary', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_vault_id'), 'devices', ['vault_id'], unique=False)
    op.create_table('vault_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('vault_key_version', sa.BigInteger(), nullable=False),
    sa.Column('crypto_protocol_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision >= 1', name='ck_snapshot_revision_positive'),
    sa.CheckConstraint('vault_key_version >= 1', name='ck_snapshot_vkv_positive'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id', 'revision', name='uq_snapshot_vault_revision')
    )
    op.create_index(op.f('ix_vault_snapshots_vault_id'), 'vault_snapshots', ['vault_id'], unique=False)
    op.create_table('device_key_envelopes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('encryption', sa.String(length=32), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('octet_length(nonce) = 12', name='ck_dke_nonce_len'),
    sa.CheckConstraint('octet_length(tag) = 16', name='ck_dke_tag_len'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id', 'device_id', 'credential_id', name='uq_dke_vault_device_credential')
    )
    op.create_index(op.f('ix_device_key_envelopes_device_id'), 'device_key_envelopes', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_key_envelopes_vault_id'), 'device_key_envelopes', ['vault_id'], unique=False)
    op.create_table('key_envelopes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('master', 'device', 'recovery', name='envelope_type'), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('kdf_algorithm', sa.String(length=32), nullable=True),
    sa.Column('kdf_version', sa.Integer(), nullable=True),
    sa.Column('kdf_memory_kib', sa.Integer(), nullable=True),
    sa.Column('kdf_iterations', sa.Integer(), nullable=True),
    sa.Column('kdf_parallelism', sa.Integer(), nullable=True),
    sa.Column('kdf_hash_len', sa.Integer(), nullable=True),
    sa.Column('kdf_salt', sa.LargeBinary(), nullable=True),
    sa.Column('encryption', sa.String(length=32), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.CheckConstraint("(type = 'device') = (device_id IS NOT NULL)", name='ck_envelope_device_id_iff_device'),
    sa.CheckConstraint("(type = 'master') = (kdf_salt IS NOT NULL)", name='ck_envelope_kdf_iff_master'),
    sa.CheckConstraint('octet_length(nonce) = 12', name='ck_envelope_nonce_len'),
    sa.CheckConstraint('octet_length(tag) = 16', name='ck_envelope_tag_len'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['vault_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'type', 'device_id', name='uq_envelope_snapshot_type_device', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_key_envelopes_snapshot_id'), 'key_envelopes', ['snapshot_id'], unique=False)
    op.create_table('vault_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('crypto_version', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.CheckConstraint('octet_length(nonce) = 12', name='ck_entry_nonce_len'),
    sa.CheckConstraint('octet_length(tag) = 16', name='ck_entry_tag_len'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['vault_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'entry_id', name='uq_entry_snapshot_entry')
    )
    op.create_index(op.f('ix_vault_entries_snapshot_id'), 'vault_entries', ['snapshot_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key_cose', sa.LargeBinary(), nullable=True),
    sa.Column('rp_id', sa.String(length=255), nullable=False),
    sa.Column('aaguid', sa.Uuid(), nullable=True),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('transports', sa.String(length=255), nullable=True),
    sa.Column('uv_required', sa.Boolean(), nullable=False),
    sa.Column('unlock_mechanism', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', name='uq_webauthn_credential_id')
    )
    op.create_index(op.f('ix_webauthn_credentials_device_id'), 'webauthn_credentials', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credentials_device_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_vault_entries_snapshot_id'), table_name='vault_entries')
    op.drop_table('vault_entries')
    op.drop_index(op.f('ix_key_envelopes_snapshot_id'), table_name='key_envelopes')
    op.drop_table('key_envelopes')
    op.drop_index(op.f('ix_device_key_envelopes_vault_id'), table_name='device_key_envelopes')
    op.drop_index(op.f('ix_device_key_envelopes_device_id'), table_name='device_key_envelopes')
    op.drop_table('device_key_envelopes')
    op.drop_index(op.f('ix_vault_snapshots_vault_id'), table_name='vault_snapshots')
    op.drop_table('vault_snapshots')
    op.drop_index(op.f('ix_devices_vault_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_vaults_user_id'), table_name='vaults')
    op.drop_table('vaults')
    op.drop_table('users')
    sa.Enum(name='envelope_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
